### ISSUE TITLE
Need to .gitignore files create by make

### ISSUE THREAD

**Issue by tomdonaldson** [ivoa-std/VOTable#11]
When `make` is run, a number of files are generated.  These should all be ignored by git so that they are not accidentally committed.

**Comment by molinaro-m** [comment]
For ConeSearch we have the .gitignore content set to:
ivoatexmeta.tex
ConeSearch.aux
ConeSearch.bbl
ConeSearch.blg
ConeSearch.log
ConeSearch.out
ConeSearch.pdf
ConeSearch.toc
ConeSearch.html
I think it could be a startingpoint.

**Comment by tomdonaldson** [comment]
Resolved by #12
