### ISSUE TITLE
Add definitions for legal COOSYS "system" values.

### ISSUE THREAD

**Issue by tomdonaldson** [ivoa-std/VOTable#22]
(This issue was first raised during the [discussion of VOTable 1.4](https://wiki.ivoa.net/twiki/bin/view/IVOA/VOTable14RFC#coosys_values).)

The legal values for the `system` attribute of `COOSYS` are listed in section 3.4 of the spec, but are not defined.  It would be helpful for implementors if we provided a table of these values that included clear definitions of the values.

**Comment by mbtaylor** [comment]
Perhaps this should use a vocabulary along the same lines as those used for the TIMESYS timescale and refposition attributes.

**Comment by BaptisteCecconi** [comment]
I concur with @mbtaylor , there is a vocabulary (draft) for the reference systems: https://www.ivoa.net/rdf/refframe/2019-03-15/refframe.html 
What we need to do is: 
- update and consolidate the vocabulary
- include the link to the vocabulary in the next VOTable revision
