### ISSUE TITLE
Add example to help explain MIN/MAX clarification

### ISSUE THREAD

**Issue by tomdonaldson** [ivoa-std/VOTable#32]
#30 Adds clarifying text on the intent of MIN and MAX for array-valued PARAMs and FIELDs.

An example illustrating MIN and MAX for each of an array, non-array and xtype value may make the text easier to digest.

**Comment by Bonnarel** [comment]
Sorry how should we understand the text in the case of SODA issue  #2 (https://github.com/ivoa-std/SODA/issues/2) which I recently tried to solve with SODA  Erratum 3 (https://wiki.ivoa.net/twiki/bin/view/IVOA/SODA10Err3). Should we understand that here there is an xtype (interval) for the BAND PARAM and that in that case interval rules should apply to the meanning of the MIN and MAX array values ?

**Comment by msdemlei** [comment]
On Thu, Jan 26, 2023 at 08:06:38AM -0800, François Bonnarel wrote:
> Sorry how should we understand the text in the case of SODA issue
> #2 (https://github.com/ivoa-std/SODA/issues/2) which I recently
> tried to solve with SODA  Erratum 3
> (https://wiki.ivoa.net/twiki/bin/view/IVOA/SODA10Err3). Should we
> understand that here there is an xtype (interval) for the BAND
> PARAM and that in that case interval rules should apply to the
> meanning of the MIN and MAX array values ?

For the interval xtype, I'd suggest to keep the standard VOTable
interpretation; that's good enough here, since the limits on both the
upper and the lower limit of the interval are identical.

In general, we'll have to define the MIN/MAX interpretation where the
xtype is defined (and yes, I wish we hadn't gone down that road).

**Comment by Bonnarel** [comment]
Le 27/01/2023 à 09:17, msdemlei a écrit :
> On Thu, Jan 26, 2023 at 08:06:38AM -0800, François Bonnarel wrote:
> > Sorry how should we understand the text in the case of SODA issue
> > #2 (https://github.com/ivoa-std/SODA/issues/2) which I recently
> > tried to solve with SODA Erratum 3
> > (https://wiki.ivoa.net/twiki/bin/view/IVOA/SODA10Err3). Should we
> > understand that here there is an xtype (interval) for the BAND
> > PARAM and that in that case interval rules should apply to the
> > meanning of the MIN and MAX array values ?
>
> For the interval xtype, I'd suggest to keep the standard VOTable
> interpretation; 

so MIN[0] will be the minimum of the lower limit and MIN[1] the minumum 
of the higher limit

And MAX[0] the maximum of the higher limit and MAX[1] the maximum of the 
higher limit ?

> that's good enough here, since the limits on both the
> upper and the lower limit of the interval are identical.

Humm. I don't understand this statement. Why should they be identical ?

Another option would be MIN contains the smaller length interval and MAX 
the higher length. I find it more immediately useful (and the 
interpretation is different)


>
> In general, we'll have to define the MIN/MAX interpretation where the
> xtype is defined (and yes, I wish we hadn't gone down that road).
>
> —
>
OK. this discussion is for the SODA erratum, not really for the VOTable 
(solved) issue, anyway.

**Comment by msdemlei** [comment]
On Fri, Jan 27, 2023 at 08:58:11AM -0800, François Bonnarel wrote:
> Le 27/01/2023 à 09:17, msdemlei a écrit :
> > For the interval xtype, I'd suggest to keep the standard VOTable
> > interpretation;
>
> so MIN[0] will be the minimum of the lower limit and MIN[1] the minumum
> of the higher limit
>
> And MAX[0] the maximum of the higher limit and MAX[1] the maximum of the
> higher limit ?

No, as laid down in the PR, MIN and MAX are as for the datatype
(i.e., atomic).  ***@***.*** is the minimal value for both the lower
and the upper limit, and ***@***.*** is the maximal value for both the
lower and the upper limit.

> > that's good enough here, since the limits on both the
> > upper and the lower limit of the interval are identical.
>
> Humm. I don't understand this statement. Why should they be identical ?

I thought there was a bit too much "limit" in this sentence, but your
following remark makes me believe we're on the same page, really.
First, if you do a cutout between 1e-14 and 2e-14 Joule, any of the
following intervals probably be good, no?

1e-14 2e-14
1e-14 1.00001e-14
1.99999e-14 2e-14

That observation made me write the statement above.  Calling the
limits of the interval "bounds", perhaps it can be written less
confusingly as: "Minimal and maximal values of either bound of the
interval are the same."

          -- Markus

**Comment by Bonnarel** [comment]
Le 31/01/2023 à 08:20, msdemlei a écrit :
> On Fri, Jan 27, 2023 at 08:58:11AM -0800, François Bonnarel wrote:
> > Le 27/01/2023 à 09:17, msdemlei a écrit :
> > > For the interval xtype, I'd suggest to keep the standard VOTable
> > > interpretation;
> >
> > so MIN[0] will be the minimum of the lower limit and MIN[1] the minumum
> > of the higher limit
> >
> > And MAX[0] the maximum of the higher limit and MAX[1] the maximum of the
> > higher limit ?
>
> No, as laid down in the PR, MIN and MAX are as for the datatype
> (i.e., atomic). ***@***.*** is the minimal value for both the lower
> and the upper limit, and ***@***.*** is the maximal value for both the
> lower and the upper limit.

Ah OK. So in these conditions the "wrong syntax" identified originally 
by Alberto Micol in the BAND example was not wrong. Was it ?

And SODA erratum 3 has to be rejected.

I comment my own SODA erratum 3 email with this option.
