### ISSUE TITLE
Update VOUnits reference to 1.1

### ISSUE THREAD

**Issue by mbtaylor** [ivoa-std/VOTable#57]
Since VOUnits 1.1 is now a RECommendation, the reference to the VOUnits standard in Sec 4.4 should be to VOUnits 1.1 rather than the existing VOUnits 1.0.  The content is not that much different, but 1.1 has a new syntax summary section that makes a friendlier introduction to readers than what was available in 1.0.

I don't think that VOUnits 1.1 has made it into ADS yet, so presumably the update will have to wait until then(?).

**Comment by msdemlei** [comment]
On Thu, Jan 18, 2024 at 02:45:33AM -0800, Mark Taylor wrote:
> I don't think that VOUnits 1.1 has made it into ADS yet, so
> presumably the update will have to wait until then(?).

It's been in the works, and it's now there.  Totally feel free to
review https://github.com/ivoa-std/ivoatex/pull/128, merge it and
then fix things here.

**Comment by tomdonaldson** [comment]
Closed with PR #58
