### ISSUE TITLE
ref problem in unit paragraph

### ISSUE THREAD

**Issue by lesidaner** [ivoa-std/VOTable#60]
After Make I have on VOTable PDF in unit pargraph        ?;
corresponding to  \citet{2023ivoa.spec.1215G};  in tex

Pierre

**Comment by mbtaylor** [comment]
Try `make biblio` and make again.

**Comment by mbtaylor** [comment]
Oops - that second make might need to be a `make forcetex`.  In general
```
make clean
make
make biblio
make forcetex
```
does the trick.  If you want the HTML as well you need `make VOTable.html`.

**Comment by tomdonaldson** [comment]
Closing this issue as the above advice seems to work.
