### ISSUE TITLE
No .vor record for inclusion of VOTable standard in RofR

### ISSUE THREAD

**Issue by theresadower** [ivoa-std/VOTable#7]
Each IVOA standard is assigned an ivoid for the purposes of reference in other standards documents; VOTable's is ivo://www.ivoa.net/std/VOTable . 

By design, the Registry of Registries should contain a VOResource representation of the standards document itself. Currently, the RofR does not include a VOTable resource. (not listed in: http://rofr.ivoa.net/oai?verb=ListRecords&metadataPrefix=ivo_vor&set=Standard). In the volute repository, this was listed in an XML file with extension .vor in the same directory as the TeX and other main documents for the standard. We should have a .vor file in the repository for each document in ivoa-std as we move to GitHub. (RegistryInterface as an example: https://github.com/ivoa-std/RegistryInterface/pull/1)

The ivoa-std VOTable repo should have a .vor file representation at the top level, kept current with the version of VOTable and passed to the maintainers of the RofR.

**Comment by tomdonaldson** [comment]
Addressed by https://github.com/ivoa-std/VOTable/pull/8
